apiVersion: v1
kind: Secret
metadata:
  name: redis
  labels:
    app: redis
type: Opaque
data:
  # Default password is 'mypassword'.
  # Use 'echo -n 'your-password' | base64' to generate a new one.
  REDIS_PASSWORD: bXlwYXNzd29yZA==
