apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # Default credentials. Replace with your own base64 encoded values.
  POSTGRES_DB: bXlkYXRhYmFzZQ==   # echo -n 'mydatabase' | base64
  POSTGRES_USER: bXl1c2Vy          # echo -n 'myuser' | base64
  POSTGRES_PASSWORD: bXlwYXNzd29yZA== # echo -n 'mypassword' | base64
