apiVersion: v1
kind: Service
metadata:
  name: atlas-catalog-backend-service
  labels:
    app: atlas-catalog-backend
spec:
  type: ClusterIP
  selector:
    app: atlas-catalog-backend
  ports:
    - name: http-alt
      port: 8080
      protocol: TCP
      targetPort: http-alt
