apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-catalog-backend
  labels:
    app.kubernetes.io/name: atlas-catalog-backend
    app.kubernetes.io/instance: atlas-catalog
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/part-of: atlas-catalog
    app: atlas-catalog-backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: atlas-catalog-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atlas-catalog-backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          envFrom:
            - secretRef:
                name: atlas-catalog-secret
          image: atlas-catalog-app:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 9000
              name: php-fpm
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: app-storage
              mountPath: /var/www/html/storage
        - name: web
          image: nginx:1.25-alpine
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: http-alt
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: app-code
          emptyDir: {}
        - name: app-storage
          persistentVolumeClaim:
            claimName: atlas-catalog-storage-pvc
        - name: nginx-config
          configMap:
            name: atlas-catalog-nginx-conf
