name: ShellCheck

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  shell-check:
    # Run on `angelcamposm/atlas-catalog` main branch, or on pull requests to prevent double-running on mirrors
    if: (github.event_name == 'pull_request' || (github.event_name == 'push' && github.repository == 'angelcamposm/atlas-catalog'))
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
